const $=id=>document.getElementById(id);
const ids=['logNumber','date','title','summary','reason','step1','step2','step3','step4','problem','solution','result','next'];
const defaults={logNumber:'4',date:new Date().toISOString().slice(0,10),title:'JISSO.LOG制作システム',summary:'投稿制作を、毎回ゼロから考えない仕組みを完成させた。',reason:'制作内容を入力するだけで、InstagramとThreadsと画像6枚をまとめて作れるようにしたい。',step1:'制作内容を入力',step2:'投稿文を自動生成',step3:'画像6枚を生成',step4:'PNGで保存',problem:'投稿ごとに文章と画像を別々に作ると、時間がかかり、トーンも揃いにくい。',solution:'入力項目を固定し、JISSO.LOGの構成・色・文章をひとつの画面で生成できるようにした。',result:'Instagramキャプション、Threads投稿、画像6枚を一度に作れるJISSO.LOG MAKERが完成。',next:'実際の制作で使いながら改善する'};
let data={};

function read(){ids.forEach(id=>data[id]=$(id).value.trim());localStorage.setItem('jisso-log-maker',JSON.stringify(data));}
function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function dateText(){return data.date.replaceAll('-','.');}
function slidesData(){const n=String(data.logNumber).padStart(3,'0');return[
 {theme:'black',label:`JISSO.LOG / ${n}`,title:`${data.title}、<br>完成<span class="accent">。</span>`,body:data.summary,giant:'.',cards:[['STATUS','COMPLETED'],['CATEGORY','CREATIVE']]},
 {theme:'',label:'START / IDEA',title:'毎回ゼロから、<br>作るのをやめたい。',body:data.reason,giant:'01'},
 {theme:'lime',label:'BUILD TIMELINE',title:'完成までの、<br>制作工程。',steps:[data.step1,data.step2,data.step3,data.step4],giant:'→'},
 {theme:'black',label:'BUILD WALL / 01',title:'途中で、<br>止まった<span class="accent">。</span>',body:`${data.problem} ${data.solution}`,giant:'!'},
 {theme:'',label:'FINISH / COMPLETED',title:`${data.title}、<br>完成<span class="accent">。</span>`,body:data.result,giant:'.',cards:[['RESULT','COMPLETED'],['STATUS','READY']]},
 {theme:'lime',label:'NEXT BUILD',title:'次の実装へ、<br>進む。',body:data.next,cards:[['STATUS','COMPLETED'],['NEXT','NEW BUILD']],giant:'→'}
];}
function slideHTML(s,i){const steps=s.steps?`<div class="timeline">${s.steps.map((x,j)=>`<div class="event"><b>0${j+1}</b><span>${esc(x)}</span></div>`).join('')}</div>`:'';const cards=s.cards?`<div class="cards">${s.cards.map(c=>`<div class="card"><small>${c[0]}</small><b>${esc(c[1])}</b></div>`).join('')}</div>`:'';return `<div class="slide-wrap"><div class="slide-meta"><span>${String(i+1).padStart(2,'0')} / 06</span><button data-download="${i}">PNG保存</button></div><article class="slide ${s.theme}"><div class="slide-top"><span><i class="mini-dot"></i>JISSO.LOG</span><span class="page">${String(i+1).padStart(2,'0')} / 06</span></div><div class="slide-content"><div class="label">${s.label}</div><h3>${s.title}</h3>${s.body?`<p>${esc(s.body)}</p>`:''}${steps}${cards}</div><div class="giant">${s.giant}</div><div class="slide-foot"><b>JISSO.</b><span class="rule"></span><span>${dateText()}</span></div></article></div>`;}
function makeCopy(){const n=String(data.logNumber).padStart(3,'0');$('instagram').value=`JISSO.LOG ${n}\n\n${data.title}、完成しました。\n\n${data.reason}\n\n実装したもの：\n・${data.step1}\n・${data.step2}\n・${data.step3}\n・${data.step4}\n\n途中で起きたこと：\n${data.problem}\n\n${data.solution}\n\n${data.result}\n\n次の実装：\n${data.next}\n\n思いつきを、今日カタチに。\n今日も、完成しました。\n\n#JISSO #実装 #完成 #制作記録 #クリエイター #自動化 #AI #JISSOLOG`;
$('threads').value=`${data.title}を作る。\n\n↓\n\n${data.step1}。\n\n↓\n\n${data.step2}。\n\n↓\n\n${data.step3}。\n\n↓\n\n${data.problem}\n\n↓\n\n${data.solution}\n\n↓\n\n${data.title}、完成。\n\n思いつきを、今日カタチに。\n今日も実装った。`;}
function render(){read();$('slides').innerHTML=slidesData().map(slideHTML).join('');makeCopy();document.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>downloadSlide(Number(b.dataset.download)));}
function wrap(ctx,text,max){const lines=[];for(const para of text.split('\n')){let line='';for(const ch of para){if(ctx.measureText(line+ch).width>max&&line){lines.push(line);line=ch}else line+=ch}lines.push(line)}return lines;}
function drawWrapped(ctx,text,x,y,max,lineHeight,maxLines=5){const lines=wrap(ctx,text,max).slice(0,maxLines);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return y+lines.length*lineHeight;}
function drawSlide(i){const s=slidesData()[i],c=document.createElement('canvas');c.width=1080;c.height=1350;const x=76,w=928;const colors={black:'#10110f',lime:'#b7ff2a',white:'#f7f7f2',gray:'#70736c'};const bg=s.theme==='black'?colors.black:s.theme==='lime'?colors.lime:colors.white;const fg=s.theme==='black'?colors.white:colors.black;const accent=s.theme==='lime'?colors.black:colors.lime;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,c.width,c.height);ctx.textBaseline='top';ctx.fillStyle=accent;ctx.beginPath();ctx.arc(84,91,9,0,Math.PI*2);ctx.fill();ctx.fillStyle=fg;ctx.font='900 20px Arial, sans-serif';ctx.fillText('JISSO.LOG',108,80);ctx.fillStyle=colors.gray;ctx.textAlign='right';ctx.fillText(`${String(i+1).padStart(2,'0')} / 06`,1004,80);ctx.textAlign='left';ctx.fillStyle=colors.gray;ctx.font='900 21px Arial, sans-serif';ctx.fillText(s.label,x,405);ctx.fillStyle=fg;ctx.font='900 72px "Noto Sans JP", Arial, sans-serif';let title=s.title.replace(/<br>/g,'\n').replace(/<[^>]+>/g,'');let y=475;for(const line of title.split('\n')){ctx.fillText(line,x,y);y+=82}if(s.body){ctx.font='700 29px "Noto Sans JP", Arial, sans-serif';y=drawWrapped(ctx,s.body,x,y+35,w,48,5)}if(s.steps){y+=25;s.steps.forEach((step,j)=>{ctx.fillStyle='#465022';ctx.font='900 24px Arial';ctx.fillText(`0${j+1}`,x,y);ctx.fillStyle=fg;ctx.font='900 37px "Noto Sans JP", Arial';ctx.fillText(step,x+150,y-8);ctx.globalAlpha=.22;ctx.fillRect(x+150,y+44,w-150,2);ctx.globalAlpha=1;y+=100})}if(s.cards){y+=35;const gap=18,cw=(w-gap)/2;s.cards.forEach((card,j)=>{const bx=x+j*(cw+gap);ctx.strokeStyle=s.theme==='black'?'#343630':'#d7d8d1';ctx.strokeRect(bx,y,cw,120);ctx.fillStyle=colors.gray;ctx.font='900 15px Arial';ctx.fillText(card[0],bx+24,y+23);ctx.fillStyle=fg;ctx.font='900 27px Arial';ctx.fillText(card[1],bx+24,y+62)})}ctx.globalAlpha=s.theme==='lime'?.28:.12;ctx.fillStyle=s.theme==='lime'?colors.white:colors.lime;ctx.font='900 330px Arial';ctx.textAlign='right';ctx.fillText(s.giant,1100,930);ctx.globalAlpha=1;ctx.textAlign='left';ctx.fillStyle=fg;ctx.font='900 20px Arial';ctx.fillText('JISSO.',x,1255);ctx.globalAlpha=.2;ctx.fillRect(178,1268,670,2);ctx.globalAlpha=1;ctx.textAlign='right';ctx.fillText(dateText(),1004,1255);return c;}
function downloadSlide(i){const a=document.createElement('a');a.download=`JISSO-LOG-${String(data.logNumber).padStart(3,'0')}-${String(i+1).padStart(2,'0')}.png`;a.href=drawSlide(i).toDataURL('image/png');a.click();toast(`${i+1}枚目を保存しました`);}
async function downloadAll(){for(let i=0;i<6;i++){downloadSlide(i);await new Promise(r=>setTimeout(r,300));}}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1800);}
function reset(){Object.entries(defaults).forEach(([k,v])=>$(k).value=v);render();}
document.addEventListener('input',e=>{if(ids.includes(e.target.id))render()});$('generate').onclick=render;$('sample').onclick=reset;$('downloadAll').onclick=downloadAll;document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText($(b.dataset.copy).value);toast('コピーしました')});
const saved=JSON.parse(localStorage.getItem('jisso-log-maker')||'null');Object.entries(saved||defaults).forEach(([k,v])=>{if($(k))$(k).value=v});if(!$('date').value)$('date').value=defaults.date;render();
