const $=id=>document.getElementById(id);const fields=['idea','done','notDoing','task1','task2','task3','task4','problem','solution','completed','nextBuild'];let current=0,minutes=45,seconds=2700,ticker=null;
function save(){const data={};fields.forEach(id=>data[id]=$(id).value);data.current=current;data.minutes=minutes;localStorage.setItem('jisso-bakusoku-sheet',JSON.stringify(data));updateProgress()}
function showStep(n){current=Math.max(0,Math.min(5,n));document.querySelectorAll('.step').forEach((el,i)=>el.classList.toggle('active',i===current));document.querySelectorAll('#nav li').forEach((el,i)=>{el.classList.toggle('active',i===current);el.classList.toggle('done',i<current)});save();document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function updateProgress(){const filled=fields.filter(id=>$(id).value.trim()).length;const value=Math.round(filled/fields.length*100);$('percent').textContent=value+'%';$('bar').style.width=value+'%'}
function timeText(){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function renderTimer(){ $('timer').textContent=timeText() }
function start(){if(ticker)return;$('timerStatus').textContent='BUILDING';ticker=setInterval(()=>{seconds--;renderTimer();if(seconds<=0){clearInterval(ticker);ticker=null;$('timerStatus').textContent='TIME UP';toast('時間です。いまの状態を完成にしましょう。')}},1000)}
function pause(){clearInterval(ticker);ticker=null;$('timerStatus').textContent='PAUSED'}
function resetTimer(){pause();seconds=minutes*60;renderTimer();$('timerStatus').textContent='READY'}
function record(){return `【JISSO. 爆速実装記録】\n\n思いつき：${$('idea').value}\n完成条件：${$('done').value}\n今日はやらない：${$('notDoing').value}\n\n工程\n01 ${$('task1').value}\n02 ${$('task2').value}\n03 ${$('task3').value}\n04 ${$('task4').value}\n\n途中で起きたこと：${$('problem').value}\n解決：${$('solution').value}\n\n完成したもの：${$('completed').value}\n次の実装：${$('nextBuild').value}\n\n思いつきを、今日カタチに。\n今日も実装った。`}
function cardLines(ctx,text,maxWidth){const lines=[];let line='';for(const ch of(text||'完成しました。')){if(ctx.measureText(line+ch).width>maxWidth&&line){lines.push(line);line=ch}else line+=ch}if(line)lines.push(line);return lines.slice(0,3)}
function downloadCompletionCard(){const c=document.createElement('canvas');c.width=1080;c.height=1350;const ctx=c.getContext('2d'),ink='#10110f',lime='#b7ff2a',white='#f7f7f2',gray='#8e918a';ctx.fillStyle=ink;ctx.fillRect(0,0,1080,1350);ctx.textBaseline='top';ctx.fillStyle=lime;ctx.beginPath();ctx.arc(85,88,9,0,Math.PI*2);ctx.fill();ctx.fillStyle=white;ctx.font='900 22px Arial,sans-serif';ctx.fillText('JISSO.',110,76);ctx.textAlign='right';ctx.fillStyle=gray;ctx.font='800 18px Arial,sans-serif';ctx.fillText('COMPLETION CARD',995,78);ctx.textAlign='left';ctx.fillStyle=gray;ctx.font='900 20px Arial,sans-serif';ctx.fillText('TODAY I BUILT',76,350);ctx.fillStyle=white;ctx.font='900 78px "Noto Sans JP",Arial,sans-serif';let y=405;cardLines(ctx,$('completed').value||$('idea').value,900).forEach(line=>{ctx.fillText(line,76,y);y+=92});ctx.fillStyle=lime;ctx.font='900 118px Arial,sans-serif';ctx.fillText('COMPLETED.',76,760);const used=Math.max(0,minutes*60-seconds),usedMin=Math.floor(used/60),usedSec=used%60,elapsed=usedMin?`${usedMin} MIN ${String(usedSec).padStart(2,'0')} SEC`:`${usedSec} SEC`;ctx.fillStyle=gray;ctx.font='900 15px Arial,sans-serif';ctx.fillText('BUILD TIME',76,955);ctx.fillText('DATE',400,955);ctx.fillText('NEXT BUILD',620,955);ctx.fillStyle=white;ctx.font='900 25px "Noto Sans JP",Arial,sans-serif';ctx.fillText(elapsed,76,990);ctx.fillText(new Date().toLocaleDateString('ja-JP').replaceAll('/','.'),400,990);ctx.font='900 22px "Noto Sans JP",Arial,sans-serif';cardLines(ctx,$('nextBuild').value||'NEW BUILD',380).slice(0,2).forEach((line,i)=>ctx.fillText(line,620,990+i*34));ctx.globalAlpha=.18;ctx.fillStyle=white;ctx.fillRect(76,1155,920,2);ctx.globalAlpha=1;ctx.fillStyle=white;ctx.font='800 25px "Noto Sans JP",Arial,sans-serif';ctx.fillText('思いつきを、今日カタチに。',76,1195);ctx.textAlign='right';ctx.fillStyle=lime;ctx.font='900 21px Arial,sans-serif';ctx.fillText('JISSO.TOOL / 001',995,1200);const a=document.createElement('a');a.download=`JISSO-COMPLETED-${new Date().toISOString().slice(0,10)}.png`;a.href=c.toDataURL('image/png');a.click();toast('完成カードを保存しました')}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>el.classList.remove('show'),2200)}
document.querySelectorAll('.next').forEach(b=>b.onclick=()=>showStep(current+1));document.querySelectorAll('#nav li').forEach(li=>li.onclick=()=>showStep(Number(li.dataset.step)));fields.forEach(id=>$(id).addEventListener('input',save));document.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-min]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');minutes=Number(b.dataset.min);resetTimer();save()});$('start').onclick=start;$('pause').onclick=pause;$('timerReset').onclick=resetTimer;$('finishNow').onclick=()=>{pause();if(!$('completed').value.trim())$('completed').value=$('idea').value;$('timerStatus').textContent='COMPLETED';save();showStep(5);toast('時間を待たず、完成へ進みます')};$('complete').onclick=()=>{if(!$('completed').value.trim())$('completed').value=$('idea').value;const completedCard=$('celebrate');completedCard.classList.add('show');save();toast('完成しました！');setTimeout(()=>completedCard.scrollIntoView({behavior:'smooth',block:'center'}),80)};$('copy').onclick=async()=>{await navigator.clipboard.writeText(record());toast('完成記録をコピーしました')};$('print').onclick=()=>window.print();$('reset').onclick=()=>{if(!confirm('入力内容をすべて消して、最初から始めますか？'))return;localStorage.removeItem('jisso-bakusoku-sheet');fields.forEach(id=>$(id).value='');minutes=45;resetTimer();$('celebrate').classList.remove('show');showStep(0)};
$('downloadCard').onclick=downloadCompletionCard;const saved=JSON.parse(localStorage.getItem('jisso-bakusoku-sheet')||'null');if(saved){fields.forEach(id=>$(id).value=saved[id]||'');minutes=saved.minutes||45;seconds=minutes*60;document.querySelectorAll('[data-min]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.min)===minutes));current=saved.current||0}renderTimer();showStep(current);updateProgress();
